window.MEDOFFICER_JOBS = [
  {
    id: "npcil-mo-c-2025",
    organization: "NPCIL",
    title: "Medical Officer/C (General Duty Medical Officer)",
    location: "Mumbai, Maharashtra",
    state: "All India",
    salary: "Level 10 | Approx. Rs. 67,700+ allowances",
    salaryBand: "60k+",
    qualification: "MBBS with relevant registration",
    vacancies: "Multiple",
    lastDate: "2025-03-04",
    postedDate: "2025-02-12",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "GDMO", "Interview", "All India"],
    verified: true,
    sourceName: "NPCIL Careers",
    sourceType: "Official recruitment portal",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:15:00+05:30",
    officialNotification: "https://npcilcareers.co.in/MainSiten/DefaultInfo.aspx",
    applyLink: "https://npcilcareers.co.in/MainSiten/DefaultInfo.aspx",
    summary: "Official NPCIL medical officer recruitment listed on the nuclear PSU careers portal.",
    featured: true
  },
  {
    id: "esic-imo-grade-ii",
    organization: "ESIC",
    title: "Insurance Medical Officer Grade-II",
    location: "Pan India",
    state: "All India",
    salary: "Level 10 | Central pay scale",
    salaryBand: "60k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-31",
    postedDate: "2025-04-10",
    selectionMode: "Written",
    sector: "Govt",
    tags: ["Govt", "ESIC", "Written", "All India"],
    verified: true,
    sourceName: "ESIC",
    sourceType: "Official government recruitment notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:05:00+05:30",
    officialNotification: "https://www.esic.gov.in/recruitments",
    applyLink: "https://www.esic.gov.in/recruitments",
    summary: "ESIC medical officer intake tracked via the official recruitments page.",
    featured: true
  },
  {
    id: "aiims-bibinagar-sr-medical",
    organization: "AIIMS Bibinagar",
    title: "Senior Resident / Medical Officer Track",
    location: "Bibinagar, Telangana",
    state: "Telangana",
    salary: "AIIMS academic pay norms",
    salaryBand: "60k+",
    qualification: "MBBS with relevant eligibility",
    vacancies: "Varies by department",
    lastDate: "2025-05-15",
    postedDate: "2025-04-18",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Telangana", "Interview", "AIIMS"],
    verified: true,
    sourceName: "AIIMS Bibinagar",
    sourceType: "Official institute notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T07:52:00+05:30",
    officialNotification: "https://aiimsbibinagar.edu.in/",
    applyLink: "https://aiimsbibinagar.edu.in/",
    summary: "Useful Telangana target source for MBBS-based hospital recruitment and contract medical roles.",
    featured: true
  },
  {
    id: "nhm-telangana-medical-officer",
    organization: "NHM Telangana",
    title: "Medical Officer",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    salary: "Contract honorarium as per state norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "District-wise",
    lastDate: "2025-05-06",
    postedDate: "2025-04-22",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Telangana", "Contract", "Interview"],
    verified: true,
    sourceName: "Telangana Health",
    sourceType: "State health department notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:11:00+05:30",
    officialNotification: "https://health.telangana.gov.in/",
    applyLink: "https://health.telangana.gov.in/",
    summary: "State-level contractual Medical Officer openings surfaced through the official health department.",
    featured: true
  },
  {
    id: "hmfw-ap-medical-officer",
    organization: "HMFW Andhra Pradesh",
    title: "Medical Officer",
    location: "Mangalagiri, Andhra Pradesh",
    state: "Andhra Pradesh",
    salary: "State contract norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "District-wise",
    lastDate: "2025-05-04",
    postedDate: "2025-04-20",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Andhra Pradesh", "Contract", "Interview"],
    verified: true,
    sourceName: "HMFW AP",
    sourceType: "Official state portal",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:08:00+05:30",
    officialNotification: "https://hmfw.ap.gov.in/",
    applyLink: "https://hmfw.ap.gov.in/",
    summary: "Andhra Pradesh HMFW remains a key high-yield source for district-level Medical Officer recruitment.",
    featured: true
  },
  {
    id: "ntpc-industrial-health-physician",
    organization: "NTPC",
    title: "Industrial / Occupational Health Medical Officer",
    location: "Across NTPC stations",
    state: "All India",
    salary: "PSU medical scale",
    salaryBand: "80k+",
    qualification: "MBBS, experience preferred",
    vacancies: "Multiple",
    lastDate: "2025-05-21",
    postedDate: "2025-04-24",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Occupational Health", "Interview", "All India"],
    verified: true,
    sourceName: "NTPC Careers",
    sourceType: "Official careers portal",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:12:00+05:30",
    officialNotification: "https://careers.ntpc.co.in/",
    applyLink: "https://careers.ntpc.co.in/",
    summary: "High-priority PSU source for plant medical and industrial health doctor roles.",
    featured: true
  },
  {
    id: "iocl-medical-officer",
    organization: "IOCL",
    title: "Medical Officer / GDMO",
    location: "Refinery and marketing units",
    state: "All India",
    salary: "PSU package with allowances",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-18",
    postedDate: "2025-04-16",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "GDMO", "Interview", "All India"],
    verified: true,
    sourceName: "IndianOil Careers",
    sourceType: "Official careers portal",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:49:00+05:30",
    officialNotification: "https://iocl.com/latest-job-opening",
    applyLink: "https://iocl.com/latest-job-opening",
    summary: "Core PSU source for refinery and location-based Medical Officer engagements.",
    featured: true
  },
  {
    id: "bpcl-medical-officer-contract",
    organization: "BPCL",
    title: "Factory Medical Officer",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    salary: "Negotiable PSU contract package",
    salaryBand: "80k+",
    qualification: "MBBS, AFIH preferred",
    vacancies: "1-2",
    lastDate: "2025-04-30",
    postedDate: "2025-04-12",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Factory Medical Officer", "Contract", "Interview"],
    verified: true,
    sourceName: "BPCL Careers",
    sourceType: "Official careers portal",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:42:00+05:30",
    officialNotification: "https://www.bharatpetroleum.in/careers/job-openings.aspx",
    applyLink: "https://www.bharatpetroleum.in/careers/job-openings.aspx",
    summary: "Refinery and occupational-health roles from the official BPCL careers stream.",
    featured: false
  },
  {
    id: "hpcl-occupational-health-doctor",
    organization: "HPCL",
    title: "Occupational Health Doctor",
    location: "Visakhapatnam, Andhra Pradesh",
    state: "Andhra Pradesh",
    salary: "PSU contract package",
    salaryBand: "80k+",
    qualification: "MBBS, industrial health profile preferred",
    vacancies: "1",
    lastDate: "2025-05-09",
    postedDate: "2025-04-14",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Occupational Health", "Andhra Pradesh", "Interview"],
    verified: true,
    sourceName: "HPCL Careers",
    sourceType: "Official careers page",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:58:00+05:30",
    officialNotification: "https://www.hindustanpetroleum.com/hpcareers/current_openings",
    applyLink: "https://www.hindustanpetroleum.com/hpcareers/current_openings",
    summary: "Important AP PSU source for refinery-side occupational and industrial medical roles.",
    featured: false
  },
  {
    id: "ongc-gdmo",
    organization: "ONGC",
    title: "General Duty Medical Officer",
    location: "Dehradun / field locations",
    state: "All India",
    salary: "Attractive fixed honorarium",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-14",
    postedDate: "2025-04-17",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "GDMO", "Interview", "All India"],
    verified: true,
    sourceName: "ONGC India",
    sourceType: "Official recruitment notice",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:01:00+05:30",
    officialNotification: "https://ongcindia.com/web/eng/career/recruitment-notice",
    applyLink: "https://ongcindia.com/web/eng/career/recruitment-notice",
    summary: "Recurring PSU medical recruitment worth monitoring closely for walk-in style GDMO hiring.",
    featured: true
  },
  {
    id: "gail-medical-officer",
    organization: "GAIL",
    title: "Medical Officer",
    location: "Vijaipur / operational units",
    state: "All India",
    salary: "PSU pay and allowances",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-11",
    postedDate: "2025-04-13",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Medical Officer", "Interview", "All India"],
    verified: true,
    sourceName: "GAIL Careers",
    sourceType: "Official PSU recruitment",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:03:00+05:30",
    officialNotification: "https://gailonline.com/CRCurrentSCform.html",
    applyLink: "https://gailonline.com/CRCurrentSCform.html",
    summary: "Plant and operational area Medical Officer roles from GAIL's official careers stream.",
    featured: false
  },
  {
    id: "hal-industrial-medical-officer",
    organization: "HAL",
    title: "Industrial Medical Officer",
    location: "Bengaluru, Karnataka",
    state: "Karnataka",
    salary: "Company doctor pay as per HAL norms",
    salaryBand: "80k+",
    qualification: "MBBS, industrial exposure desirable",
    vacancies: "1",
    lastDate: "2025-05-07",
    postedDate: "2025-04-12",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Industrial Medical Officer", "Interview"],
    verified: true,
    sourceName: "HAL India Careers",
    sourceType: "Official careers notice",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:44:00+05:30",
    officialNotification: "https://hal-india.co.in/Career_Detail.aspx?Mkey=221&lKey=&CKey=54",
    applyLink: "https://hal-india.co.in/Career_Detail.aspx?Mkey=221&lKey=&CKey=54",
    summary: "Useful aerospace PSU source for factory and industrial medicine profiles.",
    featured: false
  },
  {
    id: "bhel-medical-consultant",
    organization: "BHEL",
    title: "Part-Time Medical Consultant / Medical Officer",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    salary: "Consultant remuneration as per BHEL norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "1-2",
    lastDate: "2025-05-03",
    postedDate: "2025-04-21",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Telangana", "Consultant", "Interview"],
    verified: true,
    sourceName: "BHEL Careers",
    sourceType: "Official PSU notice",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:10:00+05:30",
    officialNotification: "https://careers.bhel.in/",
    applyLink: "https://careers.bhel.in/",
    summary: "Regularly useful Hyderabad-region PSU source for doctor consultant and MO roles.",
    featured: true
  },
  {
    id: "bel-medical-officer",
    organization: "BEL",
    title: "Medical Officer",
    location: "Bengaluru, Karnataka",
    state: "Karnataka",
    salary: "PSU scale / contract package",
    salaryBand: "60k+",
    qualification: "MBBS",
    vacancies: "1",
    lastDate: "2025-05-08",
    postedDate: "2025-04-15",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Medical Officer", "Interview"],
    verified: true,
    sourceName: "BEL Careers",
    sourceType: "Official company recruitment",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:56:00+05:30",
    officialNotification: "https://bel-india.in/job-notifications/",
    applyLink: "https://bel-india.in/job-notifications/",
    summary: "Official BEL recruitment stream often carries medical and EHS-linked doctor roles.",
    featured: false
  },
  {
    id: "sail-gdmo",
    organization: "SAIL",
    title: "General Duty Medical Officer",
    location: "Burnpur / plant hospitals",
    state: "West Bengal",
    salary: "Consolidated monthly remuneration",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-13",
    postedDate: "2025-04-18",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "GDMO", "Interview", "Contract"],
    verified: true,
    sourceName: "SAIL Careers",
    sourceType: "Official steel PSU notice",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T07:47:00+05:30",
    officialNotification: "https://www.sail.co.in/en/home",
    applyLink: "https://www.sail.co.in/en/home",
    summary: "Plant hospital GDMO recruitment from an important PSU medical employer.",
    featured: false
  },
  {
    id: "coal-india-medical-executive",
    organization: "Coal India",
    title: "Medical Executive / Sr. Medical Officer",
    location: "Coalfield units",
    state: "All India",
    salary: "E3/E4 scale",
    salaryBand: "80k+",
    qualification: "MBBS / PG as applicable",
    vacancies: "Multiple",
    lastDate: "2025-05-22",
    postedDate: "2025-04-23",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Medical Executive", "Interview", "All India"],
    verified: true,
    sourceName: "Coal India",
    sourceType: "Official recruitment page",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:14:00+05:30",
    officialNotification: "https://www.coalindia.in/career-cil/jobs-at-coal-india/",
    applyLink: "https://www.coalindia.in/career-cil/jobs-at-coal-india/",
    summary: "One of the strongest recurring PSU medical recruitment sources for MBBS doctors.",
    featured: true
  },
  {
    id: "ecl-medical-executive",
    organization: "Eastern Coalfields",
    title: "Medical Executive / Medical Specialist",
    location: "West Bengal / Jharkhand units",
    state: "All India",
    salary: "Coal PSU scale",
    salaryBand: "80k+",
    qualification: "MBBS / specialist as applicable",
    vacancies: "Multiple",
    lastDate: "2025-05-20",
    postedDate: "2025-04-24",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Medical Executive", "Interview"],
    verified: true,
    sourceName: "ECL",
    sourceType: "Official subsidiary recruitment",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:06:00+05:30",
    officialNotification: "https://easterncoal.nic.in/",
    applyLink: "https://easterncoal.nic.in/",
    summary: "Coal India subsidiary with meaningful doctor recruitment volume worth keeping in top tier.",
    featured: false
  },
  {
    id: "railway-health-medical-officer",
    organization: "Indian Railways",
    title: "General Duty Medical Officer",
    location: "Zonal railway hospitals",
    state: "All India",
    salary: "Railway contract medical remuneration",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-12",
    postedDate: "2025-04-14",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Railways", "GDMO", "Interview"],
    verified: true,
    sourceName: "Indian Railways",
    sourceType: "Official zonal notification",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T07:53:00+05:30",
    officialNotification: "https://indianrailways.gov.in/",
    applyLink: "https://indianrailways.gov.in/",
    summary: "Zonal railways regularly publish contract GDMO and hospital doctor recruitment.",
    featured: true
  },
  {
    id: "nhm-ap-specialist-mo",
    organization: "NHM Andhra Pradesh",
    title: "Medical Officer / Specialist MO",
    location: "District hospitals, Andhra Pradesh",
    state: "Andhra Pradesh",
    salary: "State contract norms",
    salaryBand: "40k+",
    qualification: "MBBS / PG as applicable",
    vacancies: "District-wise",
    lastDate: "2025-05-05",
    postedDate: "2025-04-19",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Andhra Pradesh", "Interview", "Contract"],
    verified: true,
    sourceName: "NHM AP",
    sourceType: "Official state health notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T07:59:00+05:30",
    officialNotification: "https://cfw.ap.nic.in/",
    applyLink: "https://cfw.ap.nic.in/",
    summary: "High-yield AP source for district-level Medical Officer and specialist recruitment.",
    featured: true
  },
  {
    id: "dme-telangana-assistant-professor-mo",
    organization: "DME Telangana",
    title: "Medical Officer / Teaching Hospital Contract Role",
    location: "Teaching hospitals, Telangana",
    state: "Telangana",
    salary: "Contract medical pay",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-02",
    postedDate: "2025-04-18",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Telangana", "Contract", "Interview"],
    verified: true,
    sourceName: "DME Telangana",
    sourceType: "Official medical education notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T07:54:00+05:30",
    officialNotification: "https://dme.telangana.gov.in/",
    applyLink: "https://dme.telangana.gov.in/",
    summary: "Teaching-hospital pathway for Telangana MBBS candidates via the official DME stream.",
    featured: false
  },
  {
    id: "dmho-hyderabad-mo",
    organization: "DMHO Hyderabad",
    title: "Medical Officer",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    salary: "District health contract package",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "Several",
    lastDate: "2025-04-29",
    postedDate: "2025-04-17",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Telangana", "DMHO", "Contract"],
    verified: true,
    sourceName: "District Health Department",
    sourceType: "Official district notice",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:09:00+05:30",
    officialNotification: "https://hyderabad.telangana.gov.in/",
    applyLink: "https://hyderabad.telangana.gov.in/",
    summary: "District health recruitment tracked from official Telangana district notifications.",
    featured: false
  },
  {
    id: "aiims-mangalagiri-jr-medical",
    organization: "AIIMS Mangalagiri",
    title: "Junior Medical Officer / Contract Medical Role",
    location: "Mangalagiri, Andhra Pradesh",
    state: "Andhra Pradesh",
    salary: "Institute contract norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "Varies",
    lastDate: "2025-05-10",
    postedDate: "2025-04-16",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "Andhra Pradesh", "AIIMS", "Interview"],
    verified: true,
    sourceName: "AIIMS Mangalagiri",
    sourceType: "Official institute recruitment",
    sourceConfidence: "High",
    lastChecked: "2026-04-21T08:02:00+05:30",
    officialNotification: "https://www.aiimsmangalagiri.edu.in/",
    applyLink: "https://www.aiimsmangalagiri.edu.in/",
    summary: "Relevant AP MBBS target source with regular contract and institutional doctor hiring.",
    featured: false
  },
  {
    id: "nhm-gujarat-medical-officer",
    organization: "NHM Gujarat",
    title: "Medical Officer",
    location: "Statewide, Gujarat",
    state: "Gujarat",
    salary: "State NHM salary norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-17",
    postedDate: "2025-04-21",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "NHM", "Interview", "Contract"],
    verified: true,
    sourceName: "NHM Gujarat",
    sourceType: "Official state mission portal",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:04:00+05:30",
    officialNotification: "https://arogyasathi.gujarat.gov.in/",
    applyLink: "https://arogyasathi.gujarat.gov.in/",
    summary: "Representative NHM source in the wider official-state target set.",
    featured: false
  },
  {
    id: "nhm-rajasthan-medical-officer",
    organization: "NHM Rajasthan",
    title: "Medical Officer",
    location: "Rajasthan",
    state: "Rajasthan",
    salary: "State NHM norms",
    salaryBand: "40k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-19",
    postedDate: "2025-04-21",
    selectionMode: "Interview",
    sector: "Govt",
    tags: ["Govt", "NHM", "Interview", "Contract"],
    verified: true,
    sourceName: "NHM Rajasthan",
    sourceType: "Official state recruitment page",
    sourceConfidence: "Medium",
    lastChecked: "2026-04-21T08:13:00+05:30",
    officialNotification: "https://rajswasthya.nic.in/",
    applyLink: "https://rajswasthya.nic.in/",
    summary: "Representative official-state source for broader national coverage.",
    featured: false
  },
  {
    id: "factory-medical-officer-heavy-industry",
    organization: "Heavy Engineering PSU",
    title: "Factory Medical Officer",
    location: "Ranchi, Jharkhand",
    state: "Jharkhand",
    salary: "Industrial doctor compensation",
    salaryBand: "60k+",
    qualification: "MBBS, AFIH preferred",
    vacancies: "1",
    lastDate: "2025-05-16",
    postedDate: "2025-04-20",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Factory Medical Officer", "Interview"],
    verified: false,
    sourceName: "Official company website",
    sourceType: "Corporate recruitment page",
    sourceConfidence: "Watchlist",
    lastChecked: "2026-04-21T07:41:00+05:30",
    officialNotification: "https://www.hecltd.com/",
    applyLink: "https://www.hecltd.com/",
    summary: "Tracked watchlist source awaiting full extraction validation from official notice PDF.",
    featured: false
  },
  {
    id: "psu-occupational-health-western-region",
    organization: "Western Region PSU",
    title: "Occupational Health Doctor",
    location: "Gujarat / Maharashtra industrial belt",
    state: "All India",
    salary: "Competitive PSU contract pay",
    salaryBand: "80k+",
    qualification: "MBBS",
    vacancies: "Multiple",
    lastDate: "2025-05-24",
    postedDate: "2025-04-24",
    selectionMode: "Interview",
    sector: "PSU",
    tags: ["PSU", "Occupational Health", "Contract"],
    verified: false,
    sourceName: "Official PSU careers page",
    sourceType: "Corporate notice",
    sourceConfidence: "Watchlist",
    lastChecked: "2026-04-21T07:40:00+05:30",
    officialNotification: "https://www.psuconnect.in/",
    applyLink: "https://www.psuconnect.in/",
    summary: "Watchlist row showing how low-confidence items are visually downgraded until verified.",
    featured: false
  }
];
